version: "3.2"
services:
  web:
    image: bisratawoke/http-entry-server:latest
    depends_on:
      - "splash"
    ports:
      - "80:80"
    deploy:
      replicas: 1

  splash:
    image: bisratawoke/splash:latest
    deploy:
      replicas: 1
  
  account:
    image: bisratawoke/account:latest
    deploy:
      replicas: 1

      
networks:
  defaults:
    external:
      name: overlay

